In [2]:
# Create list baseball
baseball = [180, 215, 210, 210, 188, 176, 209, 200]

# Import the numpy package as np
import numpy as np

# Create a numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out type of np_baseball
print(type(np_baseball))

<class 'numpy.ndarray'>


In [3]:
#import pandas as pd
import pandas as pd

In [6]:
data = pd.read_csv('DataMLB.csv')
data.head()

Name Team       Position  Height  Weight    Age PosCategory
0    Adam_Donachie  BAL        Catcher      74     180  22.99     Catcher
1        Paul_Bako  BAL        Catcher      74     215  34.69     Catcher
2  Ramon_Hernandez  BAL        Catcher      72     210  30.78     Catcher
3     Kevin_Millar  BAL  First_Baseman      72     210  35.43   Infielder
4      Chris_Gomez  BAL  First_Baseman      73     188  35.71   Infielder

In [8]:
data_select = pd.read_csv('DataMLB.csv', usecols=['Height', 'Weight', 'Age'])
data_select.head()

Height  Weight    Age
0      74     180  22.99
1      74     215  34.69
2      72     210  30.78
3      72     210  35.43
4      73     188  35.71

In [10]:
height_in = pd.read_csv('DataMLB.csv', usecols=['Height'])
display(height_in)

Height
0         74
1         74
2         72
3         72
4         73
...      ...
1010      73
1011      74
1012      75
1013      75
1014      73

[1015 rows x 1 columns]

In [11]:
weight_lb = pd.read_csv('DataMLB.csv', usecols=['Weight'])
display(weight_lb)

Weight
0        180
1        215
2        210
3        210
4        188
...      ...
1010     190
1011     180
1012     205
1013     190
1014     195

[1015 rows x 1 columns]

In [12]:
# Import numpy
import numpy as np

In [13]:
# Create a numpy array from height_in: np_height_in
np_height_in = np.array(height_in)

# Print out np_height_in
print(np_height_in)

# Convert np_height_in to m: np_height_m
np_height_m = np_height_in * 0.0254

# Print np_height_m
print(np_height_m)

[[74]
 [74]
 [72]
 ...
 [75]
 [75]
 [73]]
[[1.8796]
 [1.8796]
 [1.8288]
 ...
 [1.905 ]
 [1.905 ]
 [1.8542]]


In [14]:
# Create array from height_in with metric units: np_height_m
np_height_m = np.array(height_in) * 0.0254

# Create array from weight_lb with metric units: np_weight_kg
np_weight_kg = np.array(weight_lb) * 0.453592

# Calculate the BMI: bmi
bmi = np_weight_kg / np_height_m ** 2

# Print out bmi
print(bmi)

[[23.11037639]
 [27.60406069]
 [28.48080465]
 ...
 [25.62295933]
 [23.74810865]
 [25.72686361]]


In [15]:
# Calculate the BMI: bmi
np_height_m = np.array(height_in) * 0.0254
np_weight_kg = np.array(weight_lb) * 0.453592
bmi = np_weight_kg / np_height_m ** 2

# Create the light array
light = bmi < 21

# Print out light
print(light)

# Print out BMIs of all baseball players whose BMI is below 21
print(bmi[light])

[[False]
 [False]
 [False]
 ...
 [False]
 [False]
 [False]]
[20.54255679 20.54255679 20.69282047 20.69282047 20.34343189 20.34343189
 20.69282047 20.15883472 19.4984471  20.69282047 20.9205219 ]


In [16]:
# Store weight and height lists as numpy arrays
np_weight_lb = np.array(weight_lb)
np_height_in = np.array(height_in)

# Print out the weight at index 50
print(np_weight_lb[50])

# Print out sub-array of np_height_in: index 100 up to and including index 110
print(np_height_in[100:111])

[200]
[[73]
 [74]
 [72]
 [73]
 [69]
 [72]
 [73]
 [75]
 [75]
 [73]
 [72]]


In [17]:
# Create baseball, a list of lists
baseball = [[180, 78.4],
            [215, 102.7],
            [210, 98.5],
            [188, 75.2]]


# Create a 2D numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out the type of np_baseball
print(type(np_baseball))

# Print out the shape of np_baseball
print(np_baseball.shape)

<class 'numpy.ndarray'>
(4, 2)


In [18]:
# Create a 2D numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out the shape of np_baseball
print(np_baseball.shape)

(4, 2)


In [19]:
baseball = pd.read_csv('DataMLB.csv')
baseball.head()

Name Team       Position  Height  Weight    Age PosCategory
0    Adam_Donachie  BAL        Catcher      74     180  22.99     Catcher
1        Paul_Bako  BAL        Catcher      74     215  34.69     Catcher
2  Ramon_Hernandez  BAL        Catcher      72     210  30.78     Catcher
3     Kevin_Millar  BAL  First_Baseman      72     210  35.43   Infielder
4      Chris_Gomez  BAL  First_Baseman      73     188  35.71   Infielder

In [20]:
# Create np_baseball (2 cols)
np_baseball = np.array(baseball)

# Print out the 50th row of np_baseball
print(np_baseball[:50])

# Select the entire second column of np_baseball: np_weight_lb
np_weight_lb = np_baseball[:,1]

[['Adam_Donachie' 'BAL' 'Catcher' 74 180 22.99 'Catcher']
 ['Paul_Bako' 'BAL' 'Catcher' 74 215 34.69 'Catcher']
 ['Ramon_Hernandez' 'BAL' 'Catcher' 72 210 30.78 'Catcher']
 ['Kevin_Millar' 'BAL' 'First_Baseman' 72 210 35.43 'Infielder']
 ['Chris_Gomez' 'BAL' 'First_Baseman' 73 188 35.71 'Infielder']
 ['Brian_Roberts' 'BAL' 'Second_Baseman' 69 176 29.39 'Infielder']
 ['Miguel_Tejada' 'BAL' 'Shortstop' 69 209 30.77 'Infielder']
 ['Melvin_Mora' 'BAL' 'Third_Baseman' 71 200 35.07 'Infielder']
 ['Aubrey_Huff' 'BAL' 'Third_Baseman' 76 231 30.19 'Infielder']
 ['Adam_Stern' 'BAL' 'Outfielder' 71 180 27.05 'Outfielder']
 ['Jeff_Fiorentino' 'BAL' 'Outfielder' 73 188 23.88 'Outfielder']
 ['Freddie_Bynum' 'BAL' 'Outfielder' 73 180 26.96 'Outfielder']
 ['Nick_Markakis' 'BAL' 'Outfielder' 74 185 23.29 'Outfielder']
 ['Brandon_Fahey' 'BAL' 'Outfielder' 74 160 26.11 'Outfielder']
 ['Corey_Patterson' 'BAL' 'Outfielder' 69 180 27.55 'Outfielder']
 ['Jay_Payton' 'BAL' 'Outfielder' 70 185 34.27 'Outfielde

In [21]:
# Print out height of 124th player
print(np_baseball[124, 4])

210


In [22]:
# updated is available as 2D numpy array
updated = np.array(bmi)
print(updated)

[[23.11037639]
 [27.60406069]
 [28.48080465]
 ...
 [25.62295933]
 [23.74810865]
 [25.72686361]]


In [25]:
# Create np_baseball (3 cols)
baseball = pd.read_csv('DataMLB.csv', usecols=['Height', 'Weight', 'Age'])
np_baseball = np.array(baseball)

In [26]:
# Print out addition of np_baseball and updated
print(np_baseball + updated)

[[ 97.11037639 203.11037639  46.10037639]
 [101.60406069 242.60406069  62.29406069]
 [100.48080465 238.48080465  59.26080465]
 ...
 [100.62295933 230.62295933  50.81295933]
 [ 98.74810865 213.74810865  54.75810865]
 [ 98.72686361 220.72686361  53.64686361]]


In [27]:
# Create numpy array: conversion
conversion = np.array([0.0254, 0.453592, 1])

# Print out product of np_baseball and conversion
print(np_baseball * conversion)

[[ 1.8796  81.64656 22.99   ]
 [ 1.8796  97.52228 34.69   ]
 [ 1.8288  95.25432 30.78   ]
 ...
 [ 1.905   92.98636 25.19   ]
 [ 1.905   86.18248 31.01   ]
 [ 1.8542  88.45044 27.92   ]]


In [28]:
# Create np_height_in from np_baseball
np_height_in = np.array(np_baseball[:,0])

# Print out the mean of np_height_in
print(np.mean(np_height_in))

# Print out the median of np_height_in
print(np.median(np_height_in))

73.6896551724138
74.0


In [35]:
data = pd.read_csv('DataMLB.csv', usecols=['Height', 'Weight', 'Age'])
data.head()

Height  Weight    Age
0      74     180  22.99
1      74     215  34.69
2      72     210  30.78
3      72     210  35.43
4      73     188  35.71

In [36]:
# Print mean height (first column)
np_baseball = np.array(data)
avg = np.mean(np_baseball[:,0])
print("Average: " + str(avg))

# Print median height. Replace 'None'
med = np.median(np_baseball[:,0])
print("Median: " + str(med))

# Print out the standard deviation on height. Replace 'None'
stddev = np.std(np_baseball[:,0])
print("Standard Deviation: " + str(stddev))

Average: 73.6896551724138
Median: 74.0
Standard Deviation: 2.312791881046546


In [37]:
# Print out correlation between first and second column. Replace 'None'
corr = np.corrcoef(np_baseball[:,0], np_baseball[:,2])
print("Correlation: " + str(corr))

Correlation: [[ 1.         -0.08252974]
 [-0.08252974  1.        ]]


In [134]:
fifa = pd.read_csv('DataFIFA.csv')
fifa.head()

id                    name  rating position  height   foot  rare  pace  \
0    1001          Gábor Király      69        G     191  Right     0   NaN   
1  100143            Frederik Boi      65        M     184  Right     0  61.0   
2  100264         Tomasz Szewczuk      57        A     185  Right     0  65.0   
3  100325  Steeve Joseph-Reinette      63        D     180   Left     0  68.0   
4  100326            Kamel Chafni      72        M     181  Right     0  75.0   

   shooting  passing  dribbling  defending  heading  diving  handling  \
0       NaN      NaN        NaN        NaN      NaN    70.0      66.0   
1      65.0     63.0       59.0       62.0     62.0     NaN       NaN   
2      54.0     43.0       53.0       55.0     74.0     NaN       NaN   
3      38.0     51.0       46.0       64.0     71.0     NaN       NaN   
4      64.0     67.0       72.0       57.0     66.0     NaN       NaN   

   kicking  reflexes  speed  positioning  
0     63.0      74.0   35.0         66.0  
1      NaN       NaN    NaN          NaN  
2      NaN       NaN    NaN          NaN  
3      NaN       NaN    NaN          NaN  
4      NaN       NaN    NaN          NaN

In [135]:
positions = pd.read_csv('DataFIFA.csv', usecols=['position'])
heights = pd.read_csv('DataFIFA.csv', usecols=['height'])

In [136]:
print(positions, heights)

     position
0           G
1           M
2           A
3           D
4           M
...       ...
8842        A
8843        A
8844        D
8845        D
8846        M

[8847 rows x 1 columns]       height
0        191
1        184
2        185
3        180
4        181
...      ...
8842     189
8843     175
8844     183
8845     179
8846     179

[8847 rows x 1 columns]


In [140]:
# Convert positions and heights to numpy arrays: np_positions, np_heights
np_positions = np.array(positions)
np_heights = np.array(heights)

# Heights of the goalkeepers: gk_heights
gk = np_heights[np_positions == 'G']

# Heights of the other players: other_heights
others = np_heights[np_positions != 'G']

# Print out the median height of goalkeepers. Replace 'None'
print("Median height of goalkeepers: " +  str(np.median(gk)))

# Print out the median height of other players. Replace 'None'
print("Median height of other players: " + str(np.median(others)))

Median height of goalkeepers: 188.0
Median height of other players: 181.0
